### ISSUE TITLE
dynamic_aperture: Segmentation fault

### ISSUE THREAD

**Issue by vdmkshkn** [bmad-sim/bmad-ecosystem#1219]
I came across such a problem, when calculating the dynamic aperture, only one "OLD" method works. Other methods (such as "BMAD", "PTC", "MAP") fail immediately with an error.

```Parameter input file: dynamic_aperture.init
Note: Maximum number of OpenMP threads available: 12
 Number of pz points:            1
 Note: absolute time tracking is OFF!
 Data file: test.dat
[ERROR | 2024-OCT-08 08:12:45] closed_orbit_calc:
    Closed orbit not converging! error in closed orbit:   1.84E-03
    Using branch: 0:VEPP4M
[ERROR | 2024-OCT-08 08:12:45] dynamic_aperture_scan:
    CANNOT FIND CLOSED ORBIT FOR STARTING ENERGY: 0

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f269c023cda in ???
#1  0x7f269c022d75 in ???
#2  0x7f269be4fcff in ???
#3  0x40c5e0 in ???
#4  0x405f6e in ???
#5  0x7f269be39087 in ???
#6  0x7f269be3914a in ???
#7  0x405fa4 in ???
#8  0xffffffffffffffff in ???
[1]    13013 segmentation fault (core dumped)  dynamic_aperture dynamic_aperture.init
```
[file.tar.gz](https://github.com/user-attachments/files/17286053/file.tar.gz)

**Comment by DavidSagan** [comment]
Fixed.
