### ISSUE TITLE
`pipe ele:lord_slave` consistently segfaulting

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1241]
## Issue

After the fixes in #1236, it appears that `pipe ele:lord_slave` segfaults consistently.

A local debug build on the latest commit 6c4c90a886e13e4a31546c52775c0d1f902391d, as well as the latest release on conda-forge, exhibit the same behavior. 

(This snippet uses the debug build to give additional context)
```
$ tao -init $ACC_ROOT_DIR/regression_tests/pipe_test/cesr/tao.init
[MESSAGE | 2024-OCT-17 17:26:32] tao_init:
    OpenMP active with number of threads: 112

Tao> show version
Date: 2024/10/14 20:57:28

Tao> pipe ele:lord_slave 1@0>>1 model
At line 59 of file $ACC_ROOT_DIR/tao/code/tao_control_tree_list.f90
Fortran runtime error: Index '1' of dimension 1 of array 'tree' below lower bound of 2314885530818453536

Error termination. Backtrace:
#0  0x14d2caf37171 in ???
#1  0x14d2caf37d19 in ???
#2  0x14d2caf380fb in ???
#3  0x14d2d2c3184b in walk_downwards
        at $ACC_ROOT_DIR/tao/code/tao_control_tree_list.f90:59
#4  0x14d2d2c314af in tao_control_tree_list_
        at $ACC_ROOT_DIR/tao/code/tao_control_tree_list.f90:28
#5  0x14d2d2fb29fb in tao_pipe_cmd_
        at $ACC_ROOT_DIR/tao/code/tao_pipe_cmd.f90:3125
#6  0x14d2d2c26c45 in tao_command_
        at $ACC_ROOT_DIR/tao/code/tao_command.f90:469
#7  0x14d2d322ac47 in tao_top_level_
        at $ACC_ROOT_DIR/tao/code/tao_top_level.f90:93
#8  0x40115d in tao_program
        at $ACC_ROOT_DIR/tao/program/tao_program.f90:15
#9  0x401199 in main
        at $ACC_ROOT_DIR/tao/program/tao_program.f90:9
```

This is the example listed `help pipe ele:lord_slave`.

**Comment by DavidSagan** [comment]
Fixed. My Ifort compiler does not catch this problem which is why I did not notice this before.
