### ISSUE TITLE
Tao error when running with the -noplot flag

### ISSUE THREAD

**Issue by vdmkshkn** [bmad-sim/bmad-ecosystem#1341]
When running the code with the -noplot flag: the Tao program closes with an error:
```
[ERROR | 2024-DEC-04 09:48:23] tao_locate_elements:
    ELEMENT(S) NOT FOUND: END

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7ab3c61541cf in ???
#1  0x5a27d25fd991 in ???
#2  0x5a27d246363d in ???
#3  0x5a27d245ce66 in ???
#4  0x5a27d245cb04 in ???
#5  0x7ab3c613ce07 in ???
#6  0x7ab3c613cecb in ???
#7  0x5a27d245cb34 in ???
#8  0xffffffffffffffff in ???
[1]    175656 segmentation fault (core dumped)  tao -init tao.init -noplot
```
However, if you specify a flag
```
parameter[no_end_marker] = F
```
in a file with a magnetic structure, then everything works correctly. 
There is an opinion that this is the wrong behavior of the program.

[noplot_bug.zip](https://github.com/user-attachments/files/18001999/noplot_bug.zip)

**Comment by DavidSagan** [comment]
Fixed.
