### ISSUE TITLE
Segmentation fault with PyTao on second init with nonexistent lattice file

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#201]
```python
>>> from pytao import Tao
Ta>>> Tao('-lat bad')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chrisonian/Code/GitHub/pytao/pytao/tao_ctypes/core.py", line 86, in __init__
    self.init(init)
  File "/Users/chrisonian/Code/GitHub/pytao/pytao/tao_ctypes/core.py", line 126, in init
    raise ValueError(f'Unable to init Tao with: {cmd}')
ValueError: Unable to init Tao with: -lat bad
>>> Tao('-lat bad')
Segmentation fault: 11
```

**Comment by DavidSagan** [comment]
Fixed.
