### ISSUE TITLE
tao crash during lm optimization, related to hitting limits

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#217]
Unpack the following: [bug-220505a.zip](https://github.com/DavidSagan/Bmad/files/8633137/bug-220505a.zip). Then do
```
tao
Tao> call bug-220505aa.tao
Tao> call bug-220505ab.tao
```
This segfaults on the last `run lm` in the second command file:
```
Tao: run lm
Optimizing with: lm
Type ``.'' to stop the optimizer before it's finished.
[INFO] tao_dmodel_dvar_calc:
    Remaking dModel_dVar derivative matrix.
    This may take a while...

Hit upper limit of variable: ir10[2]
Hit upper limit of variable: ir10[7]
Hit lower limit of variable: ir10[10]
Hit lower limit of variable: ir10[10]
[INFO] tao_veto_vars_with_zero_dmodel:
    Data is independent of Variable: ir10[2]
    Will not use this variable in optimization.
[INFO] tao_veto_vars_with_zero_dmodel:
    Data is independent of Variable: ir10[7]
    Will not use this variable in optimization.
  Cycle      Merit   A_lambda
[WARNING] tao_limit_calc:
    VARIABLE: ir4[6]  WITH VALUE:   2.37E+02
    HAS TARGET VALUE GREATER THAN THE HIGH LIMIT OF:    1.4000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir4[11]  WITH VALUE:   2.60E+02
    HAS TARGET VALUE GREATER THAN THE HIGH LIMIT OF:    1.0000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir4[12]  WITH VALUE:  -1.12E+02
    HAS TARGET VALUE LESS THAN THE LOW LIMIT OF:   -1.0000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir4[13]  WITH VALUE:   1.19E+02
    HAS TARGET VALUE GREATER THAN THE HIGH LIMIT OF:    1.0000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir4[18]  WITH VALUE:  -1.53E+02
    HAS TARGET VALUE LESS THAN THE LOW LIMIT OF:   -1.5000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir12[7]  WITH VALUE:  -2.40E+02
    HAS TARGET VALUE LESS THAN THE LOW LIMIT OF:   -1.4000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir12[9]  WITH VALUE:  -5.69E+01
    HAS TARGET VALUE LESS THAN THE LOW LIMIT OF:    5.0000E+00
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir12[10]  WITH VALUE:  -1.01E+02
    HAS TARGET VALUE LESS THAN THE LOW LIMIT OF:   -1.0000E+02
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST
[WARNING] tao_limit_calc:
    VARIABLE: ir12[16]  WITH VALUE:  -1.09E+01
    HAS TARGET VALUE LESS THAN THE LOW LIMIT OF:    5.0000E+00
    RESETTING VARIABLE TO BE WITHIN BOUNDS & VETOING FROM OPTIMIZER LIST

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f104fa3f55f in ???
bmad-sim/bmad-ecosystem#4  0x55dbca838e3a in __tao_lm_optimizer_mod_MOD_tao_lm_optimizer
        at /home/jsberg/Software/Bmad/bmad_dist_2022_0503-0/tao/code/tao_lm_optimizer_mod.f90:116
bmad-sim/bmad-ecosystem#5  0x55dbca5bff17 in tao_run_cmd_
        at /home/jsberg/Software/Bmad/bmad_dist_2022_0503-0/tao/code/tao_run_cmd.f90:119
bmad-sim/bmad-ecosystem#6  0x55dbca22eefe in tao_command_
        at /home/jsberg/Software/Bmad/bmad_dist_2022_0503-0/tao/code/tao_command.f90:498
bmad-sim/bmad-ecosystem#7  0x55dbca229d3d in tao_top_level_
        at /home/jsberg/Software/Bmad/bmad_dist_2022_0503-0/tao/code/tao_top_level.f90:92
bmad-sim/bmad-ecosystem#8  0x55dbca2298f0 in tao_program
        at /home/jsberg/Software/Bmad/bmad_dist_2022_0503-0/tao/program/tao_program.f90:15
bmad-sim/bmad-ecosystem#9  0x55dbca22992c in main
        at /home/jsberg/Software/Bmad/bmad_dist_2022_0503-0/tao/program/tao_program.f90:9
Segmentation fault
```

**Comment by DavidSagan** [comment]
Fixed.

**Comment by jsberg-bnl** [comment]
No more crash, thanks!
