### ISSUE TITLE
Segmentation Fault when calling "write bmad"

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#376]
When trying to write an injector lattice from Tao using the "write bmad" command, I'm getting a segmentation fault:

```
Tao> write bmad test/lat.bmad
corrupted double-linked list

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f3737f21d4f in ???
bmad-sim/bmad-ecosystem#4  0x7f3737f21cbb in ???
bmad-sim/bmad-ecosystem#5  0x7f3737f23354 in ???
bmad-sim/bmad-ecosystem#6  0x7f3737f67ae6 in ???
bmad-sim/bmad-ecosystem#7  0x7f3737f6fb69 in ???
bmad-sim/bmad-ecosystem#8  0x7f3737f703fb in ???
bmad-sim/bmad-ecosystem#9  0x7f3737f7322d in ???
bmad-sim/bmad-ecosystem#10  0x7f3737f74617 in ???
bmad-sim/bmad-ecosystem#11  0x56476a54891e in ???
bmad-sim/bmad-ecosystem#12  0x56476a4dabe0 in ???
bmad-sim/bmad-ecosystem#13  0x56476a312b5d in ???
bmad-sim/bmad-ecosystem#14  0x56476a251846 in ???
bmad-sim/bmad-ecosystem#15  0x56476a009dfd in ???
bmad-sim/bmad-ecosystem#16  0x56476a0074e7 in ???
bmad-sim/bmad-ecosystem#17  0x56476a0071c7 in ???
bmad-sim/bmad-ecosystem#18  0x7f3737f0c29c in ???
bmad-sim/bmad-ecosystem#19  0x56476a0071f8 in ???
Aborted
```

Attached is a minimal working example.

[inv1.tgz](https://github.com/DavidSagan/Bmad/files/11239680/inv1.tgz)

**Comment by ColwynGulliford** [comment]
This is using Bmad via condo: 

bmad 20230414.1

**Comment by DavidSagan** [comment]
Fixed.
