### ISSUE TITLE
tao crashes on opening lattice from 'write bmad'

### ISSUE THREAD

**Issue by NicholasWTaylor** [bmad-sim/bmad-ecosystem#438]
With the attached lattice file, if I run
`tao -lat ps.bmad -slice p2_full.mar.beg:p2_full.mar.end -command "write bmad;quit"`

then I get the following error when trying to run the produced lat file:
```
tao -lat lat_1.bmad
[MESSAGE | 2023-JUL-12 02:36:01] tao_init:
    OpenMP active with number of threads: 12
[WARNING] add_superimpose:
    Superimpose is being wrapped around an open lattice for: P2.PIP03
    Set "wrap_superimpose = False" if you do not want this.
ERROR IN bmad_parser: SUPERIMPOSE OF: P2.PIP01
     WITH REFERENCE ELEMENT: PS.BEN01 IN BRANCH 0
     USES MULTIPASS REFERENCE ELEMENT BUT OFFSET PLACES IT OUT OF THE MULTIPASS REGION!
     ROOT FILE: lat_1.bmad

[ABORT | 2023-JUL-12 02:36:01] add_superimpose:
    I DO NOT KNOW HOW TO SUPERIMPOSE ELEMENT: "P2.PIP01" OF TYPE: Pipe
    UPON: "PS.BEN01" OF TYPE: Sbend
double free or corruption (out)

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f0d2bc26d5a
bmad-sim/bmad-ecosystem#4  0x7f0d2bc25ef5
bmad-sim/bmad-ecosystem#5  0x7f0d2ba5708f
bmad-sim/bmad-ecosystem#6  0x7f0d2ba5700b
bmad-sim/bmad-ecosystem#7  0x7f0d2ba36858
bmad-sim/bmad-ecosystem#8  0x7f0d2baa126d
bmad-sim/bmad-ecosystem#9  0x7f0d2baa92fb
bmad-sim/bmad-ecosystem#10  0x7f0d2baaaf9f
bmad-sim/bmad-ecosystem#11  0x7f0d2b3918b1
bmad-sim/bmad-ecosystem#12  0x7f0d2b4d92c8
bmad-sim/bmad-ecosystem#13  0x7f0d2b5ad184
bmad-sim/bmad-ecosystem#14  0x7f0d2b5ad702
bmad-sim/bmad-ecosystem#15  0x7f0d2b598a81
bmad-sim/bmad-ecosystem#16  0x7f0d2bfdc037
bmad-sim/bmad-ecosystem#17  0x7f0d2bfa50ba
bmad-sim/bmad-ecosystem#18  0x7f0d2c1a2097
bmad-sim/bmad-ecosystem#19  0x560b0dfc9094
bmad-sim/bmad-ecosystem#20  0x7f0d2ba38082
bmad-sim/bmad-ecosystem#21  0x560b0dfc90cd
bmad-sim/bmad-ecosystem#22  0xffffffffffffffff
Aborted
```
[ps.bmad.txt](https://github.com/DavidSagan/Bmad/files/12024631/ps.bmad.txt)

**Comment by DavidSagan** [comment]
@NicholasWTaylor I'm not getting this error. Please make sure that you are using the latest version of Bmad.

**Comment by NicholasWTaylor** [comment]
@DavidSagan Thanks for checking. I had done `svn up *; util/dist_build_production`. I tried doing dist_clean first and same error. I tried grabbing the latest distribution tarball (2023_0711-0) and I still get the same error. I tried building debug instead in the latest distribution and I get a slightly different error, copied below. I'm on win10/wsl2 (Ubuntu 20.04.6 LTS) btw if that matters. 
```
tao -lat lat_1.bmad
[MESSAGE | 2023-JUL-13 07:50:55] tao_init:
    OpenMP active with number of threads: 12
[WARNING] add_superimpose:
    Superimpose is being wrapped around an open lattice for: P2.PIP03
    Set "wrap_superimpose = False" if you do not want this.
ERROR IN bmad_parser: SUPERIMPOSE OF: P2.PIP01
     WITH REFERENCE ELEMENT: PS.BEN01 IN BRANCH 0
     USES MULTIPASS REFERENCE ELEMENT BUT OFFSET PLACES IT OUT OF THE MULTIPASS REGION!
     ROOT FILE: lat_1.bmad

[ABORT | 2023-JUL-13 07:50:55] add_superimpose:
    I DO NOT KNOW HOW TO SUPERIMPOSE ELEMENT: "P2.PIP01" OF TYPE: Pipe
    UPON: "PS.BEN01" OF TYPE: Sbend
At line 91 of file /home/ntaylor/bmad_dist_2023_0711-0/bmad/code/pointer_to_lord.f90
Fortran runtime error: Index '0' of dimension 1 of array 'lat%control' below lower bound of 1

Error termination. Backtrace:
#0  0x7f1f60afbd21 in ???
bmad-sim/bmad-ecosystem#4  0x7f1f60afc869 in ???
bmad-sim/bmad-ecosystem#5  0x7f1f60afcee6 in ???
bmad-sim/bmad-ecosystem#6  0x7f1f5fcac239 in pointer_to_lord_
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/code/pointer_to_lord.f90:91
bmad-sim/bmad-ecosystem#7  0x7f1f5fcca70a in retain_overlapping_lords
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/code/remove_eles_from_lat.f90:423
bmad-sim/bmad-ecosystem#8  0x7f1f5fccb61f in remove_eles_from_lat_
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/code/remove_eles_from_lat.f90:101
bmad-sim/bmad-ecosystem#9  0x7f1f5ffc4b7a in __superimpose_mod_MOD_add_superimpose
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/modules/superimpose_mod.f90:348
bmad-sim/bmad-ecosystem#10  0x7f1f601f4d16 in do_this_superimpose
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/parsing/bmad_parser_mod.f90:5432
bmad-sim/bmad-ecosystem#11  0x7f1f601f6edb in __bmad_parser_mod_MOD_parser_add_superimpose
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/parsing/bmad_parser_mod.f90:5382
bmad-sim/bmad-ecosystem#12  0x7f1f6019d23a in bmad_parser_
        at /home/ntaylor/bmad_dist_2023_0711-0/bmad/parsing/bmad_parser.f90:1013
bmad-sim/bmad-ecosystem#13  0x7f1f60fabebf in tao_init_lattice_
        at /home/ntaylor/bmad_dist_2023_0711-0/tao/code/tao_init_lattice.f90:188
bmad-sim/bmad-ecosystem#14  0x7f1f60f499b2 in tao_init_
        at /home/ntaylor/bmad_dist_2023_0711-0/tao/code/tao_init.f90:213
bmad-sim/bmad-ecosystem#15  0x7f1f613a0322 in tao_top_level_
        at /home/ntaylor/bmad_dist_2023_0711-0/tao/code/tao_top_level.f90:52
bmad-sim/bmad-ecosystem#16  0x55b69b678170 in tao_program
        at /home/ntaylor/bmad_dist_2023_0711-0/tao/program/tao_program.f90:15
bmad-sim/bmad-ecosystem#17  0x55b69b6781a9 in main
        at /home/ntaylor/bmad_dist_2023_0711-0/tao/program/tao_program.f90:9
```

**Comment by DavidSagan** [comment]
@NicholasWTaylor I am now able to reproduce. Working on a fix...

**Comment by DavidSagan** [comment]
So far discovered that round-off error and a patch with a negative drift length are causing problems...

**Comment by DavidSagan** [comment]
@NicholasWTaylor All problems fixed and a new Distribution is being made.

**Comment by NicholasWTaylor** [comment]
@DavidSagan Thank you!
