### ISSUE TITLE
tao python (and pytao) segfault on var_create with 0.2.5

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#673]
The following code ran OK with pytao 0.2.3.  However, since updating to 0.2.5 it results in a segfault.

From python:

```
from pytao import Tao

BEAMPATH = 'sc_bsyd'
OPTIONS=' -noplot'

INIT = f'-init $LCLS_LATTICE/bmad/models/{BEAMPATH}/tao.init {OPTIONS}'

tao = Tao(INIT)

tao.var_v1_create('q.QCOL0',1,1)
tao.var_create('q.QCOL0[1]','QC001', 'K1', 1, 0, 1E-4, -1E30, 1E30, 'limit', 'F','F',0.01)
#tao.var_create('q.QCOL0[2]','QC002', 'K1', 1, 0, 1E-4, -1E30, 1E30, 'limit', 'F','F',0.01)
#tao.var_create('q.QCOL0[3]','QC003', 'K1', 1, 0, 1E-4, -1E30, 1E30, 'limit', 'F','F',0.01)
#tao.var_create('q.QCOL0[4]','QC004', 'K1', 1, 0, 1E-4, -1E30, 1E30, 'limit', 'F','F',0.01)
#tao.var_create('q.QCOL0[5]','QC005', 'K1', 1, 0, 1E-4, -1E30, 1E30, 'limit', 'F','F',0.01)
```

From native tao:

```
Tao> python var_v1_create 'q.QCOL0' 1 1

Tao> python var_create q.QCOL0[1]^^QC001^^K1^^1^^0^^1e-4^^-1e30^^1e30^^limit^^F^^F^^0.01

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f944a04251f in ???
        at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#1  0x7f944a0c4881 in ???
        at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:222
#2  0x5596a12a7424 in ???
#3  0x5596a12a7b82 in ???
#4  0x5596a1327372 in ???
#5  0x5596a11b8984 in ???
#6  0x5596a11b6517 in ???
#7  0x5596a11b61d7 in ???
#8  0x7f944a029d8f in __libc_start_call_main
        at ../sysdeps/nptl/libc_start_call_main.h:58
#9  0x7f944a029e3f in __libc_start_main_impl
        at ../csu/libc-start.c:392
#10  0x5596a11b6208 in ???
Segmentation fault (core dumped)
```

**Comment by DavidSagan** [comment]
Fixed.
