### ISSUE TITLE
crash in lattice_bookkeeper if beam energy decelerated to less than 0

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#788]
On my SLAC Ubuntu machine, this code results in a segfault.  At Cornell, it yields a divide by zero bomb.

/home/ehrlichm/for_dcs/86

At SLAC:
```
 !-------------------------------------------------
 ERR_EXIT: WILL BOMB PROGRAM TO GIVE TRACEBACK...

Program received signal SIGILL: Illegal instruction.

Backtrace for this error:
#0  0x7f23aaa23960 in ???
#1  0x7f23aaa22ac5 in ???
#2  0x7f23aa64251f in ???
        at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f23aad66351 in ???
#4  0x7f23ab15fdc4 in ???
#5  0x7f23aae85034 in ???
#6  0x7f23aae81dea in ???
#7  0x7f23aae99bcb in ???
#8  0x556ff948f695 in ???
#9  0x556ff948e0ee in ???
#10  0x7f23aa629d8f in __libc_start_call_main
        at ../sysdeps/nptl/libc_start_call_main.h:58
#11  0x7f23aa629e3f in __libc_start_main_impl
        at ../csu/libc-start.c:392
#12  0x556ff948e124 in ???
#13  0xffffffffffffffff in ???
Illegal instruction (core dumped)

```

**Comment by DavidSagan** [comment]
Fixed.
