### ISSUE TITLE
getf broken on continued lines (I think)

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#938]
```
$ getf twiss_and_track_intra_ele

File: /home/jsberg/Software/Bmad/bmad-git/20240501-0/bmad/code/twiss_and_track_intra_ele.f90
!+
! Subroutine twiss_and_track_intra_ele (ele, param, l_start, l_end, track_upstream_end, track_downstream_end,
!                            orbit_start, orbit_end, ele_start, ele_end, err, compute_floor_coords, reuse_ele_end)
!
! Routine to track a particle within an element.
!
! See also:
!   twiss_and_track_from_s_to_s
!   twiss_and_track_at_s
!
! The track_upstream_end and track_downstream_end arguments determine whether edge effects are
! included. These effects include bend edge focusing and aperture checks.
!
! Input:
!   ele                  -- ele_struct: Element to track through.
!   param                -- lat_param_struct:
!   l_start              -- real(rp): Start position measured from the beginning of the element.
!   l_end                -- real(rp): Stop position measured from the beginning of the element.
!   track_upstream_end   -- logical: If True then entrance effects are included in the tracking.
!                            But only if l_start = 0 and orbit_start%location /= inside$.
!   track_downstream_end -- Logical: If True then exit effects are included in the tracking but
!                            only if l_end = ele%value(l$) (within bmad_com%significant_length tol)
!   orbit_start          -- coord_struct, optional: Starting phase space coordinates at l_start.
!   ele_start            -- ele_struct, optional: Holds the starting Twiss parameters at l_start.
!   ele_end              -- ele_struct, optional: If reuse_ele_end is set True then reuse ele_end from trancking
!                             instead of recomputing ele_end from scratch. This can save time.
!   compute_floor_coords -- logical, optional: If present and True then the global "floor" coordinates
!                             (without misalignments) will be calculated and put in ele_end%floor.
!   reuse_ele_end        -- logical, optional: If present and True, and if ele_end has the correct
!                             lonigitudianal length and key type, reuse ele_end from trancking instead of
!                             recomputing ele_end from scratch. This can save time.
!
! Output:
!   orbit_end  -- Coord_struct, optional: End phase space coordinates.
!                   If present then the orbit_start argument must also be present.
!   ele_end    -- ele_struct, optional: Holds the ending Twiss parameters at l_end (except for photons).
!                  The map (ele_end%mat6, ele_end%vec0) is map from l_start to l_end.
!                  If present, the ele_start argument must also be present.
!                  NOTE! In the calling routine, deallocate_ele_pointers must not be called on ele_end since
!                   the pointers of ele_end point to the same locations as ele.
!   err        -- logical, optional: Set True if there is a problem like
!                  the particle gets lost in tracking
!-
recursive subroutine twiss_and_track_intra_ele (ele, param, l_start, l_end, track_upstream_end, &

Traceback (most recent call last):
  File "/home/jsberg/Software/Bmad/bmad-git/20240501-0/util/getf", line 9, in <module>
    searchf.search_all('FULL')
  File "/home/jsberg/Software/Bmad/bmad-git/20240501-0/util/searchf.py", line 647, in search_all
    search_tree (dir, search_com)
  File "/home/jsberg/Software/Bmad/bmad-git/20240501-0/util/searchf.py", line 534, in search_tree
    search_file (search_base_dir, this_search_base_dir, this_file, search_com)
  File "/home/jsberg/Software/Bmad/bmad-git/20240501-0/util/searchf.py", line 486, in search_file
    if file_name[-4:] == '.f90' or file_name[-4:] == '.inc': search_f90(full_file_name, search_com)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsberg/Software/Bmad/bmad-git/20240501-0/util/searchf.py", line 333, in search_f90
    if line.rstrip()[-1] != '&': break
       ~~~~~~~~~~~~~^^^^
IndexError: string index out of range
```

**Comment by jsberg-bnl** [comment]
Looks like commit 4c9c968dd tried to change the handling of continuation lines in util/searchf.py, but this was maybe a leftover bit?

**Comment by DavidSagan** [comment]
Yes and fixed.
